import re

from app.config import PIPELINE_VERSION
from app.models.review_ir import Claim, EvidenceCard, ProgressiveReviewIR, ReviewSection, SourceRef
from app.models.source import ExtractedDocument, SourceFrame, SourceUnit


CLAIM_PATTERNS = [
    re.compile(r"\b(def\.?|definition|thm\.?|theorem|lemma|claim|example)\b", re.IGNORECASE),
    re.compile(r"\b(is|are|means|implies|decidable|recognizable|polynomial|complexity)\b", re.IGNORECASE),
]


def _clean(text: str) -> str:
    return " ".join(text.split())


def _best_units(frame: SourceFrame) -> list[SourceUnit]:
    matching = [unit for unit in frame.units if any(pattern.search(unit.text) for pattern in CLAIM_PATTERNS)]
    return matching[:4] or frame.units[:2]


def _source_ref(frame: SourceFrame, unit: SourceUnit | None = None) -> SourceRef:
    quote = _clean(unit.text if unit else frame.text)
    return SourceRef(
        source_frame_id=frame.source_frame_id,
        source_unit_id=unit.unit_id if unit else None,
        page_index=frame.index,
        bbox=unit.bbox if unit else None,
        quote=quote[:280] if quote else None,
    )


class ReviewGenerator:
    def generate(self, extracted: ExtractedDocument, outline: list[ReviewSection]) -> ProgressiveReviewIR:
        claims: list[Claim] = []
        evidence_cards: list[EvidenceCard] = []
        frame_by_id = {frame.source_frame_id: frame for frame in extracted.source_frames}

        for section in outline:
            section_claim_ids: list[str] = []
            for frame_id in section.source_frame_ids:
                frame = frame_by_id.get(frame_id)
                if not frame:
                    continue
                for unit in _best_units(frame):
                    claim_id = f"claim_{len(claims) + 1}"
                    unit_text = _clean(unit.text)
                    claim_text = self._claim_text(unit_text)
                    ref = _source_ref(frame, unit)
                    claims.append(
                        Claim(
                            claim_id=claim_id,
                            text=claim_text,
                            explanation=self._explanation(unit_text),
                            source_refs=[ref],
                            confidence=0.72,
                            tags=self._tags(unit_text),
                            progressive_level="standard",
                        )
                    )
                    section_claim_ids.append(claim_id)

                    evidence_cards.append(
                        EvidenceCard(
                            evidence_id=f"evidence_{len(evidence_cards) + 1}",
                            claim_id=claim_id,
                            title=f"Evidence from page {frame.index}",
                            evidence_text=ref.quote or unit_text[:280],
                            why_it_matters="This source excerpt anchors the generated claim to the original document.",
                            caveat="Generated by rule-based extraction; review the linked page for context.",
                            source_refs=[ref],
                        )
                    )
            section.key_claim_ids = section_claim_ids

        if not claims and extracted.source_frames:
            frame = extracted.source_frames[0]
            ref = _source_ref(frame, frame.units[0] if frame.units else None)
            claims.append(
                Claim(
                    claim_id="claim_1",
                    text=f"The document begins with: {(ref.quote or extracted.title)[:160]}",
                    explanation="Fallback claim created from the first extracted source text.",
                    source_refs=[ref],
                    confidence=0.55,
                    tags=["fallback"],
                    progressive_level="standard",
                )
            )
            evidence_cards.append(
                EvidenceCard(
                    evidence_id="evidence_1",
                    claim_id="claim_1",
                    title="Opening source text",
                    evidence_text=ref.quote or "",
                    why_it_matters="The fallback evidence keeps the review source-linked even when no obvious claims are detected.",
                    source_refs=[ref],
                )
            )
            if outline:
                outline[0].key_claim_ids = ["claim_1"]

        overview = ReviewSection(
            section_id="overview",
            title="Document Overview",
            level=0,
            summary=self._overview(extracted),
            source_frame_ids=[frame.source_frame_id for frame in extracted.source_frames[: min(3, len(extracted.source_frames))]],
            children=outline,
            key_claim_ids=[claim.claim_id for claim in claims[:5]],
        )

        return ProgressiveReviewIR(
            document_id=extracted.document_id,
            title=extracted.title,
            document_type=extracted.document_type,
            source_frames=extracted.source_frames,
            outline=[overview],
            claims=claims,
            evidence_cards=evidence_cards,
            pipeline_version=PIPELINE_VERSION,
        )

    def _overview(self, extracted: ExtractedDocument) -> str:
        page_count = len(extracted.source_frames)
        first_text = _clean(extracted.source_frames[0].text) if extracted.source_frames else ""
        summary = first_text[:420] + ("..." if len(first_text) > 420 else "")
        return f"{extracted.title} spans {page_count} page{'s' if page_count != 1 else ''}. {summary}".strip()

    def _claim_text(self, text: str) -> str:
        if not text:
            return "The document contains a source-backed point on this page."
        sentence = re.split(r"(?<=[.!?])\s+", text)[0]
        return sentence[:240] + ("..." if len(sentence) > 240 else "")

    def _explanation(self, text: str) -> str:
        if not text:
            return "This claim was derived from extracted page text."
        return f"Derived from an extracted text block: {_clean(text)[:220]}"

    def _tags(self, text: str) -> list[str]:
        lowered = text.lower()
        tags = []
        for key in ["definition", "def", "theorem", "thm", "example", "complexity", "polynomial"]:
            if key in lowered:
                tags.append("definition" if key == "def" else "theorem" if key == "thm" else key)
        return sorted(set(tags)) or ["source-linked"]

